
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "E:/cmake/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:10 (project)"
    message: |
      The system is: Windows - 10.0.19042 - AMD64
...
