
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "E:/cmake/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:1 (project)"
    message: |
      The system is: Windows - 10.0.19042 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "E:/cmake/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "E:/cmake/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "E:/cmake/share/cmake-3.26/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:1 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler:  
      Build flags: /DWIN32;/D_WINDOWS;/W3;/GR;/EHsc
      Id flags:  
      
      The output was:
      0
      Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
      Copyright (C) Microsoft Corporation. All rights reserved.
      
      Build started 9/22/2023 12:04:56 PM.
      Project "E:\\PaddleOCR\\deploy\\cpp_infer\\build\\CMakeFiles\\3.26.5\\CompilerIdCXX\\CompilerIdCXX.vcxproj" on node 1 (default targets).
      PrepareForBuild:
        Creating directory "Debug\\".
        Creating directory "Debug\\CompilerIdCXX.tlog\\".
      InitializeBuildStatus:
        Creating "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
      ClCompile:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:classic /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc141.pdb" /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X64 Debug\\CMakeCXXCompilerId.obj
        CompilerIdCXX.vcxproj -> E:\\PaddleOCR\\deploy\\cpp_infer\\build\\CMakeFiles\\3.26.5\\CompilerIdCXX\\.\\CompilerIdCXX.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_CXX_COMPILER=C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\VC\\Tools\\MSVC\\14.16.27023\\bin\\Hostx86\\x64\\cl.exe
      FinalizeBuildStatus:
        Deleting file "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild".
        Touching "Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.lastbuildstate".
      Done Building Project "E:\\PaddleOCR\\deploy\\cpp_infer\\build\\CMakeFiles\\3.26.5\\CompilerIdCXX\\CompilerIdCXX.vcxproj" (default targets).
      
      Build succeeded.
          0 Warning(s)
          0 Error(s)
      
      Time Elapsed 00:00:00.67
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
      
      The CXX compiler identification is MSVC, found in:
        E:/PaddleOCR/deploy/cpp_infer/build/CMakeFiles/3.26.5/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "E:/cmake/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "E:/cmake/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "E:/cmake/share/cmake-3.26/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:1 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler:  
      Build flags: /DWIN32;/D_WINDOWS;/W3
      Id flags:  
      
      The output was:
      0
      Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
      Copyright (C) Microsoft Corporation. All rights reserved.
      
      Build started 9/22/2023 12:04:57 PM.
      Project "E:\\PaddleOCR\\deploy\\cpp_infer\\build\\CMakeFiles\\3.26.5\\CompilerIdC\\CompilerIdC.vcxproj" on node 1 (default targets).
      PrepareForBuild:
        Creating directory "Debug\\".
        Creating directory "Debug\\CompilerIdC.tlog\\".
      InitializeBuildStatus:
        Creating "Debug\\CompilerIdC.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
      ClCompile:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:classic /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc141.pdb" /Gd /TC /FC /errorReport:queue CMakeCCompilerId.c
        CMakeCCompilerId.c
      Link:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdC.lib" /MACHINE:X64 Debug\\CMakeCCompilerId.obj
        CompilerIdC.vcxproj -> E:\\PaddleOCR\\deploy\\cpp_infer\\build\\CMakeFiles\\3.26.5\\CompilerIdC\\.\\CompilerIdC.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_C_COMPILER=C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\VC\\Tools\\MSVC\\14.16.27023\\bin\\Hostx86\\x64\\cl.exe
      FinalizeBuildStatus:
        Deleting file "Debug\\CompilerIdC.tlog\\unsuccessfulbuild".
        Touching "Debug\\CompilerIdC.tlog\\CompilerIdC.lastbuildstate".
      Done Building Project "E:\\PaddleOCR\\deploy\\cpp_infer\\build\\CMakeFiles\\3.26.5\\CompilerIdC\\CompilerIdC.vcxproj" (default targets).
      
      Build succeeded.
          0 Warning(s)
          0 Error(s)
      
      Time Elapsed 00:00:00.51
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"
      
      The C compiler identification is MSVC, found in:
        E:/PaddleOCR/deploy/cpp_infer/build/CMakeFiles/3.26.5/CompilerIdC/CompilerIdC.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "E:/cmake/share/cmake-3.26/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "E:/cmake/share/cmake-3.26/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:1 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "E:/PaddleOCR/deploy/cpp_infer/build/CMakeFiles/CMakeScratch/TryCompile-c566mn"
      binary: "E:/PaddleOCR/deploy/cpp_infer/build/CMakeFiles/CMakeScratch/TryCompile-c566mn"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /W3 /GR /EHsc"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: E:/PaddleOCR/deploy/cpp_infer/build/CMakeFiles/CMakeScratch/TryCompile-c566mn
        
        Run Build Command(s):C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/MSBuild/15.0/Bin/MSBuild.exe cmTC_df5a3.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=15.0 /v:n && Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
        Copyright (C) Microsoft Corporation. All rights reserved.
        
        Build started 9/22/2023 12:04:58 PM.
        Project "E:\\PaddleOCR\\deploy\\cpp_infer\\build\\CMakeFiles\\CMakeScratch\\TryCompile-c566mn\\cmTC_df5a3.vcxproj" on node 1 (default targets).
        PrepareForBuild:
          Creating directory "cmTC_df5a3.dir\\Debug\\".
          Creating directory "E:\\PaddleOCR\\deploy\\cpp_infer\\build\\CMakeFiles\\CMakeScratch\\TryCompile-c566mn\\Debug\\".
          Creating directory "cmTC_df5a3.dir\\Debug\\cmTC_df5a3.tlog\\".
        InitializeBuildStatus:
          Creating "cmTC_df5a3.dir\\Debug\\cmTC_df5a3.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
        ClCompile:
          C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:classic /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_df5a3.dir\\Debug\\\\" /Fd"cmTC_df5a3.dir\\Debug\\vc141.pdb" /Gd /TP /errorReport:queue "E:\\cmake\\share\\cmake-3.26\\Modules\\CMakeCXXCompilerABI.cpp"
          Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27050 for x64
          Copyright (C) Microsoft Corporation.  All rights reserved.
          
          cl /c /Zi /W3 /WX- /diagnostics:classic /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_df5a3.dir\\Debug\\\\" /Fd"cmTC_df5a3.dir\\Debug\\vc141.pdb" /Gd /TP /errorReport:queue "E:\\cmake\\share\\cmake-3.26\\Modules\\CMakeCXXCompilerABI.cpp"
          CMakeCXXCompilerABI.cpp
          
        Link:
          C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"E:\\PaddleOCR\\deploy\\cpp_infer\\build\\CMakeFiles\\CMakeScratch\\TryCompile-c566mn\\Debug\\cmTC_df5a3.exe" /INCREMENTAL /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"E:/PaddleOCR/deploy/cpp_infer/build/CMakeFiles/CMakeScratch/TryCompile-c566mn/Debug/cmTC_df5a3.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"E:/PaddleOCR/deploy/cpp_infer/build/CMakeFiles/CMakeScratch/TryCompile-c566mn/Debug/cmTC_df5a3.lib" /MACHINE:X64  /machine:x64 cmTC_df5a3.dir\\Debug\\CMakeCXXCompilerABI.obj
          cmTC_df5a3.vcxproj -> E:\\PaddleOCR\\deploy\\cpp_infer\\build\\CMakeFiles\\CMakeScratch\\TryCompile-c566mn\\Debug\\cmTC_df5a3.exe
        FinalizeBuildStatus:
          Deleting file "cmTC_df5a3.dir\\Debug\\cmTC_df5a3.tlog\\unsuccessfulbuild".
          Touching "cmTC_df5a3.dir\\Debug\\cmTC_df5a3.tlog\\cmTC_df5a3.lastbuildstate".
        Done Building Project "E:\\PaddleOCR\\deploy\\cpp_infer\\build\\CMakeFiles\\CMakeScratch\\TryCompile-c566mn\\cmTC_df5a3.vcxproj" (default targets).
        
        Build succeeded.
            0 Warning(s)
            0 Error(s)
        
        Time Elapsed 00:00:00.97
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "E:/cmake/share/cmake-3.26/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "E:/cmake/share/cmake-3.26/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:1 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "E:/PaddleOCR/deploy/cpp_infer/build/CMakeFiles/CMakeScratch/TryCompile-473mmx"
      binary: "E:/PaddleOCR/deploy/cpp_infer/build/CMakeFiles/CMakeScratch/TryCompile-473mmx"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS /W3"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: E:/PaddleOCR/deploy/cpp_infer/build/CMakeFiles/CMakeScratch/TryCompile-473mmx
        
        Run Build Command(s):C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/MSBuild/15.0/Bin/MSBuild.exe cmTC_150e3.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=15.0 /v:n && Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
        Copyright (C) Microsoft Corporation. All rights reserved.
        
        Build started 9/22/2023 12:04:59 PM.
        Project "E:\\PaddleOCR\\deploy\\cpp_infer\\build\\CMakeFiles\\CMakeScratch\\TryCompile-473mmx\\cmTC_150e3.vcxproj" on node 1 (default targets).
        PrepareForBuild:
          Creating directory "cmTC_150e3.dir\\Debug\\".
          Creating directory "E:\\PaddleOCR\\deploy\\cpp_infer\\build\\CMakeFiles\\CMakeScratch\\TryCompile-473mmx\\Debug\\".
          Creating directory "cmTC_150e3.dir\\Debug\\cmTC_150e3.tlog\\".
        InitializeBuildStatus:
          Creating "cmTC_150e3.dir\\Debug\\cmTC_150e3.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
        ClCompile:
          C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:classic /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_150e3.dir\\Debug\\\\" /Fd"cmTC_150e3.dir\\Debug\\vc141.pdb" /Gd /TC /errorReport:queue "E:\\cmake\\share\\cmake-3.26\\Modules\\CMakeCCompilerABI.c"
          Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27050 for x64
          Copyright (C) Microsoft Corporation.  All rights reserved.
          
          cl /c /Zi /W3 /WX- /diagnostics:classic /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_150e3.dir\\Debug\\\\" /Fd"cmTC_150e3.dir\\Debug\\vc141.pdb" /Gd /TC /errorReport:queue "E:\\cmake\\share\\cmake-3.26\\Modules\\CMakeCCompilerABI.c"
          CMakeCCompilerABI.c
          
        Link:
          C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"E:\\PaddleOCR\\deploy\\cpp_infer\\build\\CMakeFiles\\CMakeScratch\\TryCompile-473mmx\\Debug\\cmTC_150e3.exe" /INCREMENTAL /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"E:/PaddleOCR/deploy/cpp_infer/build/CMakeFiles/CMakeScratch/TryCompile-473mmx/Debug/cmTC_150e3.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"E:/PaddleOCR/deploy/cpp_infer/build/CMakeFiles/CMakeScratch/TryCompile-473mmx/Debug/cmTC_150e3.lib" /MACHINE:X64  /machine:x64 cmTC_150e3.dir\\Debug\\CMakeCCompilerABI.obj
          cmTC_150e3.vcxproj -> E:\\PaddleOCR\\deploy\\cpp_infer\\build\\CMakeFiles\\CMakeScratch\\TryCompile-473mmx\\Debug\\cmTC_150e3.exe
        FinalizeBuildStatus:
          Deleting file "cmTC_150e3.dir\\Debug\\cmTC_150e3.tlog\\unsuccessfulbuild".
          Touching "cmTC_150e3.dir\\Debug\\cmTC_150e3.tlog\\cmTC_150e3.lastbuildstate".
        Done Building Project "E:\\PaddleOCR\\deploy\\cpp_infer\\build\\CMakeFiles\\CMakeScratch\\TryCompile-473mmx\\cmTC_150e3.vcxproj" (default targets).
        
        Build succeeded.
            0 Warning(s)
            0 Error(s)
        
        Time Elapsed 00:00:00.62
        
      exitCode: 0
...
